### ISSUE TITLE
Automatic Language Detection

### ISSUE THREAD

**Issue by DecimalTurn** [pulibrary/ExcelAlmaLookup#13]
### Expected behavior

This repo should be marked as a VBA repo.

### Actual behavior

This repo appears as a VB6 repo.

![image](https://github.com/user-attachments/assets/b4e82cbf-6e8a-4cd9-8888-894782e7fc7f)

### Steps to replicate

Just look at the repo's page: https://github.com/pulibrary/ExcelAlmaLookup

### Impact of this bug
This can create a little bit of confusion regarding what this project is about.

### How to solve the issue

Firstly, adding the VBA metadata that normally appears at the top of exported files should help resolve the issue for the .frm file and some .bas file. Was there a reason why this metadata was removed?

Secondly, if the problem remains for .bas files, I've documented 3 ways to solve this issue [here](https://github.com/DecimalTurn/VBA-on-GitHub/blob/main/TROUBLESHOOTING.md#what-to-do-when-vba-code-in-bas-files-is-detected-as-vb6-on-github). Let me know if you have a preference and if you want my assistance to implement the fix.

Cheers!

**Comment by tventimi** [comment]
Thanks for pointing that out.  I have been using the pre-commit script described below to extract the source code from the XLAM file before committing to github:

https://www.xltrail.com/blog/auto-export-vba-commit-hook

This seemed like the simplest approach at the time, but please let me know if there is a better way.  For the time being, I followed your suggestion C and renamed the main code module "Catalog.bas" to "Catalog.vba".  It seems that github is now recognizing most of the code as VBA.  Please let me know if it looks OK on your end.  Thanks again.

Tom

**Comment by DecimalTurn** [comment]
>  Please let me know if it looks OK on your end.

It does look good!

> [...] please let me know if there is a better way

There are certainly other ways to extract/export VBA from an XLAM file, but if you are happy with your current approach, I'd say there's no need to change to a whole new approach.

However, looking at the python script you are using, I'd suggest to replace this part:

```python
                if line.startswith('Attribute') and 'VB_' in line:
                    if 'VB_Name' in line and KEEP_NAME:
                        content.append(line)
                else:
                    content.append(line)
```
with this only:
```python
                    content.append(line)
```
This way you'll preserve the VBA metadata and it will help GitHub-Linguist identify that it's VBA code and you (almost certainly) won't need to change the file extension from `.bas` to `.vba`.

**Comment by tventimi** [comment]
Thanks very much for your help!
