### ISSUE TITLE
Digitally sign installer

### ISSUE THREAD

**Issue by tventimi** [pulibrary/ExcelAlmaLookup#6]
Some users receive the warning "Windows protected your PC" upon running the installer.  Look into digitally signing  the installer EXE to prevent this warning from appearing.

**Comment by tventimi** [comment]
Reported by a user today:

We're attempting to download the installer at
https://github.com/pulibrary/ExcelAlmaLookup?tab=readme-ov-file#readme
but our anti-virus packages are giving us warnings and errors that this
package "is not normally downloaded" and "do we trust it."

**Comment by dlingley** [comment]
Also encountered this issue at Purdue.  The Cisco antivirus is blocking the download.  Perhaps digitally signing will allow it to download?

**Comment by tventimi** [comment]
Thank you for letting me know that your antivirus program is also blocking the "Excel Alma Lookup" plugin.  I actually just obtained a code-signing certificate for this tool, which I hope will solve this problem.  However, since we are not experiencing this issue at Princeton, I will need to ask users from other institutions to confirm whether the certificate works.  I have attached a signed version of the installer to the latest release.  Could you please download it using the link below and see if you are able to install it?

https://github.com/pulibrary/ExcelAlmaLookup/releases/download/v1.1.2/CatalogLookupInstallerSigned.exe

This is not a new release, just a signed version of v1.1.2.  It is otherwise identical to that version.

Also, I found out that the certificate will not necessarily prevent the Windows SmartScreen (aka "Windows Protected your PC") alert.  Fortunately, such an alert can be bypassed by the user.  But please let me know if your antivirus program is still blocking this signed version of the plugin.  Thanks for your help and patience.
